title: Minimal theme
logo: /assets/images/background4.png
description: What in the Human Condition is worthy of being written in stone? A personal emergent journey into the esoteric made Open Source
theme: jekyll-theme-minimal
plugins:
  - jekyll-sitemap
  - jekyll-titles-from-headings